### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by PotatoeTrainYT** [CLADevs/CLAMasks#1]
CLAMasks TODO List:
- [ ] Make configurable
  - [ ] Config
  - [ ] Mask Texture
  - [ ] Mask Name
  - [ ] Effects

**Comment by PotatoeTrainYT** [comment]
Config will look something like this:
```yaml
---
masks:
  skeleton:
    name: Skeleton
    texture: SKELETON
    effects:
     - SPEED:1
     - JUMP_BOOST:1
...
```
